remote_theme : mmistakes/minimal-mistakes
minimal_mistakes_skin : "default"
url : "https://entrylevelsoftwareengineer.github.io/"
baseurl : ""
locale : "en-US"
title : "Life of Entry Level Software Engineer"
title_separator : "-"
name : "ELSE"
description : "Life of Entry Level Software Engineer. Started as an entry. Always as an etry."